### ISSUE TITLE
PVP isn't working[BUG]

### ISSUE THREAD

**Issue by HaddenBat** [ShaneBeeStudios/HungerGames#13] opened 2020-05-13 00:40 UTC
**Describe the bug**
After the grace period ends, you cant damage other players.

**To Reproduce**
Use BungeeCord, have Multiverse installed on the Spigot server, have HungerGames on the Spigot server.

**Expected behavior**
You cant hurt any players.

**Version Info:**
 - **Plugin Version:** 
4.13.9
 - **Server Version/Platform**
Spigot 1.15.2 on a Raspberry Pi 4
**Additional context**
PVP is turned on in server.properties, the join sign is only working for oped players, I set the center of the shrinking border but it is shrinking to somewhere else.

**Comment by ShaneBeee** [comment] 2020-05-13 00:41
Any other plugins that could hinder PVP?
Such as world guard?

**Comment by HaddenBat** [comment] 2020-05-13 00:45
No, the only other plugin is SSX-Connector which connects all of my BungeeCord servers so in the main lobby you can use a compass to go to different servers.

**Comment by ShaneBeee** [comment] 2020-05-13 00:46
Hmm... not sure then, I can not replicate this issue. PvP works fine on my server and the rest of the servers running this plugin.

My guess is some plugin or something is blocking PVP

**Comment by HaddenBat** [comment] 2020-05-13 00:49
do you want to see any files?

**Comment by ShaneBeee** [comment] 2020-05-13 00:49
No, because HungerGames doesn't block PVP.
So unless you have console errors to show, this is a user error.

It doesn't help that you're running a 1.15.2 server on a PI.

**Comment by HaddenBat** [comment] 2020-05-13 01:02
[latest.log](https://github.com/ShaneBeeStudios/HungerGames/files/4619211/latest.log)

**Comment by HaddenBat** [comment] 2020-05-13 01:02
i dont know if this will help.

**Comment by ShaneBeee** [comment] 2020-05-13 01:03
seems like your server is having some major issues. Those are not related to HG

**Comment by HaddenBat** [comment] 2020-05-13 01:04
Maybe because i imported this world.

**Comment by HaddenBat** [comment] 2020-05-13 01:11
Should i completely reset the HungerGames server?
Also, with the border, i dont think the arena is completely square, does that matter?

**Comment by ShaneBeee** [comment] 2020-05-13 01:14
> Should i completely reset the HungerGames server?

I dunno, Ive been told a server won't work properly on a PI, so that's probably a huge issue you're having.

> Also, with the border, i dont think the arena is completely square, does that matter?

Nope doesn't matter

**Comment by HaddenBat** [comment] 2020-05-13 01:21
> I dunno, Ive been told a server won't work properly on a PI, so that's probably a huge issue you're having.
My other servers: Bedwars and 2 Survival servers work fine. Maybe I'm setting it up wrong, is the video still current?

**Comment by ShaneBeee** [comment] 2020-05-13 01:33
Yes, it should all work the same.

**Comment by HaddenBat** [comment] 2020-05-13 01:54
when setting up the server with multiverse, is the Lobby server the main one, or is the Arena the main one?

**Comment by ShaneBeee** [comment] 2020-05-23 21:03
Closing as I can not reproduce this issue.

**Closed by ShaneBeee** 2020-05-23 21:03 UTC
Labels: can not reproduce
